//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIS_174867.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cours
    {
        public int CourseID { get; set; }
        [Required]
        public string CourseName { get; set; }
        [Required]
        public string CourseCredits { get; set; }
        [Required]
        public Nullable<int> DeptID { get; set; }

        public virtual Department Department { get; set; }
        public virtual CoursesTaught CoursesTaught { get; set; }
        public virtual CourseSubject CourseSubject { get; set; }
    }
}
