//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIS_174867.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CoursesTaught
    {
        [Required]
        public int CourseID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        [Required]
        public Nullable<int> SubjectID { get; set; }
        [Required]
        public Nullable<System.DateTime> FirstDateTaught { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
