//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIS_174867.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public int DegreeID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string Degree1 { get; set; }
        public string Specialization { get; set; }
        public Nullable<System.DateTime> DegreeYear { get; set; }
        public string Grade { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
